[0m17:00:18.476430 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67B7CF5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67B2B30B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67AC40260>]}


============================== 17:00:18.479904 | 26d12d7d-5ad3-4232-b82e-483fcd412495 ==============================
[0m17:00:18.479904 [info ] [MainThread]: Running with dbt=1.10.13
[0m17:00:18.481198 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run -s fact_committee_contribution', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\scott\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m17:00:18.484093 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\project\fec\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:00:18.485137 [debug] [MainThread]: Command `dbt run` failed at 17:00:18.485137 after 0.18 seconds
[0m17:00:18.485137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67BDF7110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67B5C9400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C67B5C9CA0>]}
[0m17:00:18.486133 [debug] [MainThread]: Flushing usage events
[0m17:00:19.058643 [debug] [MainThread]: An error was encountered while trying to flush usage events
